# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
locale                   : "en-US"
title                    : Torgo
email                    : matt@tros.org
description              : "Torgo"
baseurl                  : "/torgo" # the subpath of your site, e.g. /blog
url                      : "http://tros.org"

twitter_username         : matt_aguirre
github_username          : ZenHarbinger

# Build settings
markdown: kramdown
timezone: America/New_York
paginate: 5

# https://jekyllrb.com/docs/configuration/
# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

sass:
    sass_dir: _sass

# Social Sharing
twitter:
  username               : matt_aguirre
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :

# Google AdSense
google_ad_client         :
google_ad_slot           :

# Site Author
author:
  name             : "Matthew Aguirre"
  avatar           : "bio-photo.png"
  bio              : "This space intentionally left blank."
  location         : "Bristow, VA"
  email            : "matt@tros.org"
  uri              : "http://tros.org/"
  bitbucket        : "matt_aguirre"
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "ZenHarbinger"
  goodreads        : "ZenHarbinger"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "matthewaguirre"
  pinterest        :
  soundcloud       :
  stackoverflow    : "3533119/zenharbinger"
  steam            : "ZenHarbinger"
  tumblr           :
  twitter          : "matt_aguirre"
  vine             :
  weibo            :
  xing             :
  youtube          : "ZenHarbinger"

# Plugins
gems:
  - jekyll-paginate
  # - jekyll-coffeescript
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  # - jekyll-coffeescript
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jemoji

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
display-tag-cloud: false
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
